name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Install required utilities (including unzip)
      - name: Install required utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      # Step 3: Install JDK 17
      - name: Install JDK 17
        run: |
          sudo apt-get install -y openjdk-17-jdk
          java -version

      # Step 4: Set JAVA_HOME environment variable
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      # Step 5: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: tools, platform-tools, build-tools;30.0.3, platforms;android-30
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          PATH: $JAVA_HOME/bin:$PATH
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      # Step 6: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 7: Install Buildozer and dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get install -y \
            python3-pip \
            python3-dev \
            build-essential \
            libssl-dev \
            libffi-dev \
            libncurses5-dev \
            libsqlite3-dev \
            libreadline-dev \
            libbz2-dev \
            liblzma-dev \
            zlib1g-dev \
            libxml2-dev \
            libxslt1-dev \
            tk-dev
          python -m pip install --upgrade pip
          python -m pip install cython buildozer

      # Step 8: Build APK
      - name: Build APK
        run: |
          buildozer android debug

      # Step 9: Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: bin/*.apk
