name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Adjust this to your desired branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.12 (or the Python version you need)
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install Buildozer dependencies, including distutils
      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            zip \
            unzip \
            openjdk-8-jdk \
            libncurses5-dev \
            libstdc++6 \
            zlib1g-dev \
            liblzma-dev \
            pkg-config \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            libxml2-dev \
            libxslt1-dev \
            tk-dev \
            python3-setuptools \
            python3-pip \
            curl \
            git \
            python3-distutils  # Install distutils for Python 3.12 explicitly
          
          # Double-checking distutils for Python 3.12 (sometimes, it doesn't install correctly)
          sudo apt-get install -y python3-distutils-extra
          
          # Install pip and Buildozer
          python -m pip install --upgrade pip
          pip install buildozer

          # Check Python version and if distutils is available
          python --version
          python -c "import distutils; print(distutils.__file__)"

      # Step 4: Build APK using Buildozer
      - name: Build APK
        run: |
          buildozer android debug  # Run buildozer to build the APK (adjust flags if needed)

      # Step 5: Upload the generated APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: bin/*.apk  # This will upload any APK found in the bin folder
