name: Android Build

on:
  push:
    branches:
      - main

jobs:
  setup_android_sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            build-tools;30.0.3
            platforms;android-30
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Verify Android SDK installation
        run: |
          echo "Listing installed SDK components"
          sdkmanager --list

      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install specific SDK components
        run: |
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Update SDK Manager
        run: |
          sdkmanager --update

      - name: Run your build commands
        run: |
          # Add your build commands here (e.g., gradle build)
          echo "Build process here"
