name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3.11-venv python3.11-distutils python3.11-dev \
            build-essential libssl-dev libffi-dev zlib1g-dev \
            openjdk-17-jdk unzip wget
          sudo apt install -y libgl1-mesa-dev libgles2-mesa-dev

      # Step 4: Set up Buildozer dependencies
      - name: Install Buildozer and dependencies
        run: |
          python3.11 -m pip install --upgrade pip setuptools wheel
          python3.11 -m pip install buildozer cython

      # Step 5: Set up Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/.buildozer/android/platform/
          mv $HOME/.buildozer/android/platform/cmdline-tools $HOME/.buildozer/android/platform/tools
          echo "export ANDROID_HOME=$HOME/.buildozer/android/platform" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      # Step 6: Configure Buildozer
      - name: Prepare Buildozer spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # Step 7: Build APK
      - name: Build APK
        run: |
          buildozer android debug

      # Step 8: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk
