name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install required system packages
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev zlib1g-dev \
              libbz2-dev libreadline-dev libsqlite3-dev curl llvm \
              libncurses5-dev libncursesw5-dev xz-utils tk-dev \
              libxml2-dev libxmlsec1-dev liblzma-dev zip unzip

      # Step 4: Install buildozer and dependencies
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

    

      # Step 5: Build the APK
      - name: Build APK
        run: |
          buildozer android debug
