name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          ant \
          git \
          python3-pip \
          python3-setuptools \
          python3-dev \
          libssl-dev \
          libffi-dev \
          build-essential \
          zip \
          unzip \
          sdkmanager \
          wget
        # Install Android SDK command-line tools
        mkdir -p $HOME/Android/Sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O /tmp/cmdline-tools.zip
        unzip -q /tmp/cmdline-tools.zip -d $HOME/Android/Sdk
        rm /tmp/cmdline-tools.zip
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> ~/.bashrc
        echo "export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/tools/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc
        sdkmanager --licenses
        sdkmanager "build-tools;29.0.3" "platform-tools"
        # Install AIDL (if necessary)
        sdkmanager "platform-tools"

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Install AIDL
      run: |
        sdkmanager "build-tools;29.0.3" "platform-tools"
        
    - name: Build APK using Buildozer
      run: |
        buildozer android debug
