name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Adjust this to your desired branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.12 (or the Python version you need)
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install required dependencies, including unzip
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            zip \
            unzip \
            openjdk-8-jdk \
            libncurses5-dev \
            libstdc++6 \
            zlib1g-dev \
            liblzma-dev \
            pkg-config \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            libxml2-dev \
            libxslt1-dev \
            tk-dev \
            python3-setuptools \
            python3-pip \
            curl \
            git

      # Step 4: Install JDK 17 (to resolve the SDK manager error)
      - name: Install JDK 17
        run: |
          sudo apt-get install -y openjdk-17-jdk
          java -version

      # Step 5: Set JAVA_HOME environment variable
      - name: Set JAVA_HOME to JDK 17
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

      # Step 6: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platform-tools,platforms;android-30,build-tools;30.0.3'
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      # Step 7: Install Cython and Buildozer
      - name: Install Buildozer and Cython
        run: |
          python -m pip install cython  # Install Cython, which is missing
          python -m pip install buildozer  # Install Buildozer

      # Step 8: Build APK using Buildozer
      - name: Build APK
        run: |
          buildozer android debug  # Run buildozer to build the APK (adjust flags if needed)

      # Step 9: Upload the generated APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: bin/*.apk  # This will upload any APK found in the bin folder
