name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Adjust this to your desired branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.12 (or the Python version you need)
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install Buildozer and Android SDK dependencies
      - name: Install Buildozer and Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            zip \
            unzip \
            openjdk-8-jdk \
            libncurses5-dev \
            libstdc++6 \
            zlib1g-dev \
            liblzma-dev \
            pkg-config \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            libxml2-dev \
            libxslt1-dev \
            tk-dev \
            python3-setuptools \
            python3-pip \
            curl \
            git

          # Install the Android SDK Command Line Tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          rm commandlinetools.zip

          # Ensure the directory structure is correct (avoid moving latest into itself)
          if [ ! -d "$HOME/android-sdk/cmdline-tools/latest" ]; then
            mkdir -p $HOME/android-sdk/cmdline-tools/latest
          fi

          # Move files into the latest directory
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/

          # Set the SDK path
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          
          # Install the required SDK components
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "tools"

          # Install Cython
          python -m pip install cython  # Install Cython, which is missing

          # Install Buildozer
          python -m pip install buildozer
          
          # Check the installed versions
          python --version
          buildozer --version
          sdkmanager --version

      # Step 4: Build APK using Buildozer
      - name: Build APK
        run: |
          buildozer android debug  # Run buildozer to build the APK (adjust flags if needed)

      # Step 5: Upload the generated APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: bin/*.apk  # This will upload any APK found in the bin folder
