name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Change the Linux version here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zlib1g-dev libncurses5-dev libgdbm-dev \
          libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl \
          libbz2-dev unzip openjdk-11-jdk
        pip install --upgrade pip
        pip install buildozer

    - name: Install Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o cmdline-tools.zip
        unzip -q cmdline-tools.zip -d ~/.buildozer/android/platform/
        mkdir -p ~/.buildozer/android/platform/cmdline-tools/latest
        # Move all contents of cmdline-tools into latest/ folder, without moving the 'latest' folder itself
        mv ~/.buildozer/android/platform/cmdline-tools/* ~/.buildozer/android/platform/cmdline-tools/latest/
        yes | ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;21.3.6528147"

    - name: Build APK
      run: |
        buildozer -v android debug
